version: "3"

vars:
  FRONTENDS: frontend-home frontend-pos frontend-admin frontend-tenant

dotenv:
  - .env
  - .env.example

tasks:
  # --- Setup Tasks ---
  install:
    desc: Install all dependencies for Go and Vue
    cmds:
      - go mod download
      - for: { var: FRONTENDS }
        cmd: cd apps/{{.ITEM}} && pnpm install

  format:frontends:
    desc: Format all Node projects
    cmds:
      - for: { var: FRONTENDS }
        cmd: cd apps/{{.ITEM}} && pnpm format

  format:
    desc: Format all projects
    deps: [format:frontends]

  # --- Infrastructure ---
  infra:
    desc: Start Docker containers (DB, Redis, Mailpit, etc.)
    cmds:
      - docker compose up -d

  infra:down:
    desc: Drop Docker containers
    cmds:
      - docker compose down

  infra:kill:
    desc: Destroy all Docker containers and volumes
    cmds:
      - docker compose down -v

  # --- Linting ---
  lint:backend:
    dir: apps/backend
    cmds:
      - golangci-lint run

  # --- Testing ---
  test:backend:
    dir: apps/backend
    cmds:
      - gotestsum -f testdox -- -coverprofile=./coverage.out $(go list ./... | grep -vE "/mocks|/postgres|/docs")

  test:backend:coverage:
    dir: apps/backend
    cmds:
      - gocovsh -sort-by-coverage

  # --- Development ---
  dev:
    desc: Start all services natively with hot-reload
    deps: [infra, dev:backend, dev:frontends]

  dev:backend:
    dir: apps/backend
    cmds:
      - air

  dev:frontends:
    desc: Start all Vue apps in parallel
    deps: [install]
    cmds:
      - pnpm -r --parallel dev --host

  # --- Build & Types ---
  generate:
    desc: Generate sqlc types and swaggo
    dir: apps/backend
    cmds:
      - sqlc generate
      - swag f
      - swag i

  build:ui:
    desc: Build packages/ui
    cmds:
      - pnpm --filter @foodbasket/ui build

  build:backend:
    desc: Run docker build on backend
    dir: apps/backend
    cmds:
      - docker build -t foodbasket-backend .

  build:home:
    desc: Run docker build on frontend-home
    dir: apps/frontend-home
    cmds:
      - docker build -t foodbasket-frontend-home .

  build:tenant:
    desc: Run docker build on frontend-tenant
    dir: apps/frontend-tenant
    cmds:
      - docker build -t foodbasket-frontend-tenant .

  build:
    desc: Build Dockerfiles
    deps: [build:backend, build:home, build:tenant]
