// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetAllTenants(ctx context.Context) ([]Tenant, error)
	GetTenants(ctx context.Context, arg GetTenantsParams) ([]Tenant, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserPermissions(ctx context.Context, arg GetUserPermissionsParams) ([]string, error)
}

var _ Querier = (*Queries)(nil)
