// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenant_queries.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const getAllTenants = `-- name: GetAllTenants :many
SELECT id, name, slug, created_at, updated_at, deleted_at FROM tenants
WHERE deleted_at IS NULL
ORDER BY id
`

func (q *Queries) GetAllTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, getAllTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenant
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, slug, created_at, updated_at, deleted_at FROM tenants
WHERE deleted_at IS NULL AND id = $1
LIMIT 1
`

func (q *Queries) GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, name, slug, created_at, updated_at, deleted_at FROM tenants
WHERE deleted_at IS NULL AND LOWER(slug) = LOWER($1)
LIMIT 1
`

func (q *Queries) GetTenantBySlug(ctx context.Context, lower string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, lower)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTenants = `-- name: GetTenants :many
SELECT id, name, slug, created_at, updated_at, deleted_at FROM tenants
WHERE deleted_at IS NULL
ORDER BY id
OFFSET $1 LIMIT $2
`

type GetTenantsParams struct {
	Offset int32
	Limit  int32
}

func (q *Queries) GetTenants(ctx context.Context, arg GetTenantsParams) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, getTenants, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenant
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
