// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"luny.dev/foodbasket/internal/postgres"
)

// NewMockQuerier creates a new instance of MockQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuerier {
	mock := &MockQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQuerier is an autogenerated mock type for the Querier type
type MockQuerier struct {
	mock.Mock
}

type MockQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuerier) EXPECT() *MockQuerier_Expecter {
	return &MockQuerier_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockQuerier
func (_mock *MockQuerier) CreateUser(ctx context.Context, arg postgres.CreateUserParams) (postgres.User, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 postgres.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, postgres.CreateUserParams) (postgres.User, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, postgres.CreateUserParams) postgres.User); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(postgres.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, postgres.CreateUserParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockQuerier_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - arg postgres.CreateUserParams
func (_e *MockQuerier_Expecter) CreateUser(ctx interface{}, arg interface{}) *MockQuerier_CreateUser_Call {
	return &MockQuerier_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, arg)}
}

func (_c *MockQuerier_CreateUser_Call) Run(run func(ctx context.Context, arg postgres.CreateUserParams)) *MockQuerier_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 postgres.CreateUserParams
		if args[1] != nil {
			arg1 = args[1].(postgres.CreateUserParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_CreateUser_Call) Return(user postgres.User, err error) *MockQuerier_CreateUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockQuerier_CreateUser_Call) RunAndReturn(run func(ctx context.Context, arg postgres.CreateUserParams) (postgres.User, error)) *MockQuerier_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllTenants provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetAllTenants(ctx context.Context) ([]postgres.Tenant, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTenants")
	}

	var r0 []postgres.Tenant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]postgres.Tenant, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []postgres.Tenant); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]postgres.Tenant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetAllTenants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllTenants'
type MockQuerier_GetAllTenants_Call struct {
	*mock.Call
}

// GetAllTenants is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQuerier_Expecter) GetAllTenants(ctx interface{}) *MockQuerier_GetAllTenants_Call {
	return &MockQuerier_GetAllTenants_Call{Call: _e.mock.On("GetAllTenants", ctx)}
}

func (_c *MockQuerier_GetAllTenants_Call) Run(run func(ctx context.Context)) *MockQuerier_GetAllTenants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQuerier_GetAllTenants_Call) Return(tenants []postgres.Tenant, err error) *MockQuerier_GetAllTenants_Call {
	_c.Call.Return(tenants, err)
	return _c
}

func (_c *MockQuerier_GetAllTenants_Call) RunAndReturn(run func(ctx context.Context) ([]postgres.Tenant, error)) *MockQuerier_GetAllTenants_Call {
	_c.Call.Return(run)
	return _c
}

// GetTenantByID provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetTenantByID(ctx context.Context, id uuid.UUID) (postgres.Tenant, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTenantByID")
	}

	var r0 postgres.Tenant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (postgres.Tenant, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) postgres.Tenant); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(postgres.Tenant)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetTenantByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTenantByID'
type MockQuerier_GetTenantByID_Call struct {
	*mock.Call
}

// GetTenantByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockQuerier_Expecter) GetTenantByID(ctx interface{}, id interface{}) *MockQuerier_GetTenantByID_Call {
	return &MockQuerier_GetTenantByID_Call{Call: _e.mock.On("GetTenantByID", ctx, id)}
}

func (_c *MockQuerier_GetTenantByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockQuerier_GetTenantByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetTenantByID_Call) Return(tenant postgres.Tenant, err error) *MockQuerier_GetTenantByID_Call {
	_c.Call.Return(tenant, err)
	return _c
}

func (_c *MockQuerier_GetTenantByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (postgres.Tenant, error)) *MockQuerier_GetTenantByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTenantBySlug provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetTenantBySlug(ctx context.Context, lower string) (postgres.Tenant, error) {
	ret := _mock.Called(ctx, lower)

	if len(ret) == 0 {
		panic("no return value specified for GetTenantBySlug")
	}

	var r0 postgres.Tenant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (postgres.Tenant, error)); ok {
		return returnFunc(ctx, lower)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) postgres.Tenant); ok {
		r0 = returnFunc(ctx, lower)
	} else {
		r0 = ret.Get(0).(postgres.Tenant)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, lower)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetTenantBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTenantBySlug'
type MockQuerier_GetTenantBySlug_Call struct {
	*mock.Call
}

// GetTenantBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - lower string
func (_e *MockQuerier_Expecter) GetTenantBySlug(ctx interface{}, lower interface{}) *MockQuerier_GetTenantBySlug_Call {
	return &MockQuerier_GetTenantBySlug_Call{Call: _e.mock.On("GetTenantBySlug", ctx, lower)}
}

func (_c *MockQuerier_GetTenantBySlug_Call) Run(run func(ctx context.Context, lower string)) *MockQuerier_GetTenantBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetTenantBySlug_Call) Return(tenant postgres.Tenant, err error) *MockQuerier_GetTenantBySlug_Call {
	_c.Call.Return(tenant, err)
	return _c
}

func (_c *MockQuerier_GetTenantBySlug_Call) RunAndReturn(run func(ctx context.Context, lower string) (postgres.Tenant, error)) *MockQuerier_GetTenantBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// GetTenants provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetTenants(ctx context.Context, arg postgres.GetTenantsParams) ([]postgres.Tenant, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetTenants")
	}

	var r0 []postgres.Tenant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, postgres.GetTenantsParams) ([]postgres.Tenant, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, postgres.GetTenantsParams) []postgres.Tenant); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]postgres.Tenant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, postgres.GetTenantsParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetTenants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTenants'
type MockQuerier_GetTenants_Call struct {
	*mock.Call
}

// GetTenants is a helper method to define mock.On call
//   - ctx context.Context
//   - arg postgres.GetTenantsParams
func (_e *MockQuerier_Expecter) GetTenants(ctx interface{}, arg interface{}) *MockQuerier_GetTenants_Call {
	return &MockQuerier_GetTenants_Call{Call: _e.mock.On("GetTenants", ctx, arg)}
}

func (_c *MockQuerier_GetTenants_Call) Run(run func(ctx context.Context, arg postgres.GetTenantsParams)) *MockQuerier_GetTenants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 postgres.GetTenantsParams
		if args[1] != nil {
			arg1 = args[1].(postgres.GetTenantsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetTenants_Call) Return(tenants []postgres.Tenant, err error) *MockQuerier_GetTenants_Call {
	_c.Call.Return(tenants, err)
	return _c
}

func (_c *MockQuerier_GetTenants_Call) RunAndReturn(run func(ctx context.Context, arg postgres.GetTenantsParams) ([]postgres.Tenant, error)) *MockQuerier_GetTenants_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetUserByEmail(ctx context.Context, email string) (postgres.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 postgres.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (postgres.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) postgres.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(postgres.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockQuerier_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockQuerier_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *MockQuerier_GetUserByEmail_Call {
	return &MockQuerier_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *MockQuerier_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockQuerier_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetUserByEmail_Call) Return(user postgres.User, err error) *MockQuerier_GetUserByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockQuerier_GetUserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (postgres.User, error)) *MockQuerier_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserPermissions provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetUserPermissions(ctx context.Context, arg postgres.GetUserPermissionsParams) ([]string, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPermissions")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, postgres.GetUserPermissionsParams) ([]string, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, postgres.GetUserPermissionsParams) []string); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, postgres.GetUserPermissionsParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetUserPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserPermissions'
type MockQuerier_GetUserPermissions_Call struct {
	*mock.Call
}

// GetUserPermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - arg postgres.GetUserPermissionsParams
func (_e *MockQuerier_Expecter) GetUserPermissions(ctx interface{}, arg interface{}) *MockQuerier_GetUserPermissions_Call {
	return &MockQuerier_GetUserPermissions_Call{Call: _e.mock.On("GetUserPermissions", ctx, arg)}
}

func (_c *MockQuerier_GetUserPermissions_Call) Run(run func(ctx context.Context, arg postgres.GetUserPermissionsParams)) *MockQuerier_GetUserPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 postgres.GetUserPermissionsParams
		if args[1] != nil {
			arg1 = args[1].(postgres.GetUserPermissionsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetUserPermissions_Call) Return(strings []string, err error) *MockQuerier_GetUserPermissions_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockQuerier_GetUserPermissions_Call) RunAndReturn(run func(ctx context.Context, arg postgres.GetUserPermissionsParams) ([]string, error)) *MockQuerier_GetUserPermissions_Call {
	_c.Call.Return(run)
	return _c
}
