// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockIPasswordService creates a new instance of MockIPasswordService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPasswordService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPasswordService {
	mock := &MockIPasswordService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIPasswordService is an autogenerated mock type for the IPasswordService type
type MockIPasswordService struct {
	mock.Mock
}

type MockIPasswordService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPasswordService) EXPECT() *MockIPasswordService_Expecter {
	return &MockIPasswordService_Expecter{mock: &_m.Mock}
}

// HashPassword provides a mock function for the type MockIPasswordService
func (_mock *MockIPasswordService) HashPassword(password string) (string, error) {
	ret := _mock.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for HashPassword")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(password)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPasswordService_HashPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashPassword'
type MockIPasswordService_HashPassword_Call struct {
	*mock.Call
}

// HashPassword is a helper method to define mock.On call
//   - password string
func (_e *MockIPasswordService_Expecter) HashPassword(password interface{}) *MockIPasswordService_HashPassword_Call {
	return &MockIPasswordService_HashPassword_Call{Call: _e.mock.On("HashPassword", password)}
}

func (_c *MockIPasswordService_HashPassword_Call) Run(run func(password string)) *MockIPasswordService_HashPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIPasswordService_HashPassword_Call) Return(s string, err error) *MockIPasswordService_HashPassword_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockIPasswordService_HashPassword_Call) RunAndReturn(run func(password string) (string, error)) *MockIPasswordService_HashPassword_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyPassword provides a mock function for the type MockIPasswordService
func (_mock *MockIPasswordService) VerifyPassword(hash string, password string) (bool, error) {
	ret := _mock.Called(hash, password)

	if len(ret) == 0 {
		panic("no return value specified for VerifyPassword")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return returnFunc(hash, password)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(hash, password)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(hash, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPasswordService_VerifyPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyPassword'
type MockIPasswordService_VerifyPassword_Call struct {
	*mock.Call
}

// VerifyPassword is a helper method to define mock.On call
//   - hash string
//   - password string
func (_e *MockIPasswordService_Expecter) VerifyPassword(hash interface{}, password interface{}) *MockIPasswordService_VerifyPassword_Call {
	return &MockIPasswordService_VerifyPassword_Call{Call: _e.mock.On("VerifyPassword", hash, password)}
}

func (_c *MockIPasswordService_VerifyPassword_Call) Run(run func(hash string, password string)) *MockIPasswordService_VerifyPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIPasswordService_VerifyPassword_Call) Return(b bool, err error) *MockIPasswordService_VerifyPassword_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockIPasswordService_VerifyPassword_Call) RunAndReturn(run func(hash string, password string) (bool, error)) *MockIPasswordService_VerifyPassword_Call {
	_c.Call.Return(run)
	return _c
}
