// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockIRandomService creates a new instance of MockIRandomService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRandomService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRandomService {
	mock := &MockIRandomService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIRandomService is an autogenerated mock type for the IRandomService type
type MockIRandomService struct {
	mock.Mock
}

type MockIRandomService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRandomService) EXPECT() *MockIRandomService_Expecter {
	return &MockIRandomService_Expecter{mock: &_m.Mock}
}

// GenerateRandomBytes provides a mock function for the type MockIRandomService
func (_mock *MockIRandomService) GenerateRandomBytes(keySize uint) ([]byte, error) {
	ret := _mock.Called(keySize)

	if len(ret) == 0 {
		panic("no return value specified for GenerateRandomBytes")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) ([]byte, error)); ok {
		return returnFunc(keySize)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) []byte); ok {
		r0 = returnFunc(keySize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(keySize)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRandomService_GenerateRandomBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateRandomBytes'
type MockIRandomService_GenerateRandomBytes_Call struct {
	*mock.Call
}

// GenerateRandomBytes is a helper method to define mock.On call
//   - keySize uint
func (_e *MockIRandomService_Expecter) GenerateRandomBytes(keySize interface{}) *MockIRandomService_GenerateRandomBytes_Call {
	return &MockIRandomService_GenerateRandomBytes_Call{Call: _e.mock.On("GenerateRandomBytes", keySize)}
}

func (_c *MockIRandomService_GenerateRandomBytes_Call) Run(run func(keySize uint)) *MockIRandomService_GenerateRandomBytes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIRandomService_GenerateRandomBytes_Call) Return(bytes []byte, err error) *MockIRandomService_GenerateRandomBytes_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockIRandomService_GenerateRandomBytes_Call) RunAndReturn(run func(keySize uint) ([]byte, error)) *MockIRandomService_GenerateRandomBytes_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateSecretToken provides a mock function for the type MockIRandomService
func (_mock *MockIRandomService) GenerateSecretToken(tokenSize uint) (string, error) {
	ret := _mock.Called(tokenSize)

	if len(ret) == 0 {
		panic("no return value specified for GenerateSecretToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) (string, error)); ok {
		return returnFunc(tokenSize)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) string); ok {
		r0 = returnFunc(tokenSize)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(tokenSize)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRandomService_GenerateSecretToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateSecretToken'
type MockIRandomService_GenerateSecretToken_Call struct {
	*mock.Call
}

// GenerateSecretToken is a helper method to define mock.On call
//   - tokenSize uint
func (_e *MockIRandomService_Expecter) GenerateSecretToken(tokenSize interface{}) *MockIRandomService_GenerateSecretToken_Call {
	return &MockIRandomService_GenerateSecretToken_Call{Call: _e.mock.On("GenerateSecretToken", tokenSize)}
}

func (_c *MockIRandomService_GenerateSecretToken_Call) Run(run func(tokenSize uint)) *MockIRandomService_GenerateSecretToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIRandomService_GenerateSecretToken_Call) Return(s string, err error) *MockIRandomService_GenerateSecretToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockIRandomService_GenerateSecretToken_Call) RunAndReturn(run func(tokenSize uint) (string, error)) *MockIRandomService_GenerateSecretToken_Call {
	_c.Call.Return(run)
	return _c
}
