// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"luny.dev/foodbasket/internal/postgres"
)

// NewMockIUserService creates a new instance of MockIUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIUserService {
	mock := &MockIUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIUserService is an autogenerated mock type for the IUserService type
type MockIUserService struct {
	mock.Mock
}

type MockIUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIUserService) EXPECT() *MockIUserService_Expecter {
	return &MockIUserService_Expecter{mock: &_m.Mock}
}

// CheckUserCredentials provides a mock function for the type MockIUserService
func (_mock *MockIUserService) CheckUserCredentials(ctx context.Context, email string, password string) (bool, error) {
	ret := _mock.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for CheckUserCredentials")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, email, password)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserService_CheckUserCredentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckUserCredentials'
type MockIUserService_CheckUserCredentials_Call struct {
	*mock.Call
}

// CheckUserCredentials is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *MockIUserService_Expecter) CheckUserCredentials(ctx interface{}, email interface{}, password interface{}) *MockIUserService_CheckUserCredentials_Call {
	return &MockIUserService_CheckUserCredentials_Call{Call: _e.mock.On("CheckUserCredentials", ctx, email, password)}
}

func (_c *MockIUserService_CheckUserCredentials_Call) Run(run func(ctx context.Context, email string, password string)) *MockIUserService_CheckUserCredentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIUserService_CheckUserCredentials_Call) Return(b bool, err error) *MockIUserService_CheckUserCredentials_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockIUserService_CheckUserCredentials_Call) RunAndReturn(run func(ctx context.Context, email string, password string) (bool, error)) *MockIUserService_CheckUserCredentials_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterUser provides a mock function for the type MockIUserService
func (_mock *MockIUserService) RegisterUser(ctx context.Context, name string, email string, password string) (postgres.User, error) {
	ret := _mock.Called(ctx, name, email, password)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 postgres.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (postgres.User, error)); ok {
		return returnFunc(ctx, name, email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) postgres.User); ok {
		r0 = returnFunc(ctx, name, email, password)
	} else {
		r0 = ret.Get(0).(postgres.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, name, email, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserService_RegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUser'
type MockIUserService_RegisterUser_Call struct {
	*mock.Call
}

// RegisterUser is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - email string
//   - password string
func (_e *MockIUserService_Expecter) RegisterUser(ctx interface{}, name interface{}, email interface{}, password interface{}) *MockIUserService_RegisterUser_Call {
	return &MockIUserService_RegisterUser_Call{Call: _e.mock.On("RegisterUser", ctx, name, email, password)}
}

func (_c *MockIUserService_RegisterUser_Call) Run(run func(ctx context.Context, name string, email string, password string)) *MockIUserService_RegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIUserService_RegisterUser_Call) Return(user postgres.User, err error) *MockIUserService_RegisterUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIUserService_RegisterUser_Call) RunAndReturn(run func(ctx context.Context, name string, email string, password string) (postgres.User, error)) *MockIUserService_RegisterUser_Call {
	_c.Call.Return(run)
	return _c
}
