// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIValkeyService creates a new instance of MockIValkeyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIValkeyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIValkeyService {
	mock := &MockIValkeyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIValkeyService is an autogenerated mock type for the IValkeyService type
type MockIValkeyService struct {
	mock.Mock
}

type MockIValkeyService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIValkeyService) EXPECT() *MockIValkeyService_Expecter {
	return &MockIValkeyService_Expecter{mock: &_m.Mock}
}

// Del provides a mock function for the type MockIValkeyService
func (_mock *MockIValkeyService) Del(ctx context.Context, keys ...string) error {
	var tmpRet mock.Arguments
	if len(keys) > 0 {
		tmpRet = _mock.Called(ctx, keys)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Del")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) error); ok {
		r0 = returnFunc(ctx, keys...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIValkeyService_Del_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Del'
type MockIValkeyService_Del_Call struct {
	*mock.Call
}

// Del is a helper method to define mock.On call
//   - ctx context.Context
//   - keys ...string
func (_e *MockIValkeyService_Expecter) Del(ctx interface{}, keys ...interface{}) *MockIValkeyService_Del_Call {
	return &MockIValkeyService_Del_Call{Call: _e.mock.On("Del",
		append([]interface{}{ctx}, keys...)...)}
}

func (_c *MockIValkeyService_Del_Call) Run(run func(ctx context.Context, keys ...string)) *MockIValkeyService_Del_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockIValkeyService_Del_Call) Return(err error) *MockIValkeyService_Del_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIValkeyService_Del_Call) RunAndReturn(run func(ctx context.Context, keys ...string) error) *MockIValkeyService_Del_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockIValkeyService
func (_mock *MockIValkeyService) Get(ctx context.Context, key string) (string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIValkeyService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockIValkeyService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockIValkeyService_Expecter) Get(ctx interface{}, key interface{}) *MockIValkeyService_Get_Call {
	return &MockIValkeyService_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockIValkeyService_Get_Call) Run(run func(ctx context.Context, key string)) *MockIValkeyService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIValkeyService_Get_Call) Return(s string, err error) *MockIValkeyService_Get_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockIValkeyService_Get_Call) RunAndReturn(run func(ctx context.Context, key string) (string, error)) *MockIValkeyService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Sadd provides a mock function for the type MockIValkeyService
func (_mock *MockIValkeyService) Sadd(ctx context.Context, key string, members ...string) error {
	var tmpRet mock.Arguments
	if len(members) > 0 {
		tmpRet = _mock.Called(ctx, key, members)
	} else {
		tmpRet = _mock.Called(ctx, key)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Sadd")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...string) error); ok {
		r0 = returnFunc(ctx, key, members...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIValkeyService_Sadd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sadd'
type MockIValkeyService_Sadd_Call struct {
	*mock.Call
}

// Sadd is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - members ...string
func (_e *MockIValkeyService_Expecter) Sadd(ctx interface{}, key interface{}, members ...interface{}) *MockIValkeyService_Sadd_Call {
	return &MockIValkeyService_Sadd_Call{Call: _e.mock.On("Sadd",
		append([]interface{}{ctx, key}, members...)...)}
}

func (_c *MockIValkeyService_Sadd_Call) Run(run func(ctx context.Context, key string, members ...string)) *MockIValkeyService_Sadd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		var variadicArgs []string
		if len(args) > 2 {
			variadicArgs = args[2].([]string)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockIValkeyService_Sadd_Call) Return(err error) *MockIValkeyService_Sadd_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIValkeyService_Sadd_Call) RunAndReturn(run func(ctx context.Context, key string, members ...string) error) *MockIValkeyService_Sadd_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockIValkeyService
func (_mock *MockIValkeyService) Set(ctx context.Context, key string, val string, ttl time.Duration) error {
	ret := _mock.Called(ctx, key, val, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, key, val, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIValkeyService_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockIValkeyService_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - val string
//   - ttl time.Duration
func (_e *MockIValkeyService_Expecter) Set(ctx interface{}, key interface{}, val interface{}, ttl interface{}) *MockIValkeyService_Set_Call {
	return &MockIValkeyService_Set_Call{Call: _e.mock.On("Set", ctx, key, val, ttl)}
}

func (_c *MockIValkeyService_Set_Call) Run(run func(ctx context.Context, key string, val string, ttl time.Duration)) *MockIValkeyService_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIValkeyService_Set_Call) Return(err error) *MockIValkeyService_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIValkeyService_Set_Call) RunAndReturn(run func(ctx context.Context, key string, val string, ttl time.Duration) error) *MockIValkeyService_Set_Call {
	_c.Call.Return(run)
	return _c
}

// SetNx provides a mock function for the type MockIValkeyService
func (_mock *MockIValkeyService) SetNx(ctx context.Context, key string, val string, ttl time.Duration) error {
	ret := _mock.Called(ctx, key, val, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetNx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, key, val, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIValkeyService_SetNx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNx'
type MockIValkeyService_SetNx_Call struct {
	*mock.Call
}

// SetNx is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - val string
//   - ttl time.Duration
func (_e *MockIValkeyService_Expecter) SetNx(ctx interface{}, key interface{}, val interface{}, ttl interface{}) *MockIValkeyService_SetNx_Call {
	return &MockIValkeyService_SetNx_Call{Call: _e.mock.On("SetNx", ctx, key, val, ttl)}
}

func (_c *MockIValkeyService_SetNx_Call) Run(run func(ctx context.Context, key string, val string, ttl time.Duration)) *MockIValkeyService_SetNx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIValkeyService_SetNx_Call) Return(err error) *MockIValkeyService_SetNx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIValkeyService_SetNx_Call) RunAndReturn(run func(ctx context.Context, key string, val string, ttl time.Duration) error) *MockIValkeyService_SetNx_Call {
	_c.Call.Return(run)
	return _c
}

// SetXx provides a mock function for the type MockIValkeyService
func (_mock *MockIValkeyService) SetXx(ctx context.Context, key string, val string, ttl time.Duration) error {
	ret := _mock.Called(ctx, key, val, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetXx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, key, val, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIValkeyService_SetXx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetXx'
type MockIValkeyService_SetXx_Call struct {
	*mock.Call
}

// SetXx is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - val string
//   - ttl time.Duration
func (_e *MockIValkeyService_Expecter) SetXx(ctx interface{}, key interface{}, val interface{}, ttl interface{}) *MockIValkeyService_SetXx_Call {
	return &MockIValkeyService_SetXx_Call{Call: _e.mock.On("SetXx", ctx, key, val, ttl)}
}

func (_c *MockIValkeyService_SetXx_Call) Run(run func(ctx context.Context, key string, val string, ttl time.Duration)) *MockIValkeyService_SetXx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIValkeyService_SetXx_Call) Return(err error) *MockIValkeyService_SetXx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIValkeyService_SetXx_Call) RunAndReturn(run func(ctx context.Context, key string, val string, ttl time.Duration) error) *MockIValkeyService_SetXx_Call {
	_c.Call.Return(run)
	return _c
}

// Sismember provides a mock function for the type MockIValkeyService
func (_mock *MockIValkeyService) Sismember(ctx context.Context, key string, val string) (bool, error) {
	ret := _mock.Called(ctx, key, val)

	if len(ret) == 0 {
		panic("no return value specified for Sismember")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, key, val)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, key, val)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, key, val)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIValkeyService_Sismember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sismember'
type MockIValkeyService_Sismember_Call struct {
	*mock.Call
}

// Sismember is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - val string
func (_e *MockIValkeyService_Expecter) Sismember(ctx interface{}, key interface{}, val interface{}) *MockIValkeyService_Sismember_Call {
	return &MockIValkeyService_Sismember_Call{Call: _e.mock.On("Sismember", ctx, key, val)}
}

func (_c *MockIValkeyService_Sismember_Call) Run(run func(ctx context.Context, key string, val string)) *MockIValkeyService_Sismember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIValkeyService_Sismember_Call) Return(b bool, err error) *MockIValkeyService_Sismember_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockIValkeyService_Sismember_Call) RunAndReturn(run func(ctx context.Context, key string, val string) (bool, error)) *MockIValkeyService_Sismember_Call {
	_c.Call.Return(run)
	return _c
}

// Smembers provides a mock function for the type MockIValkeyService
func (_mock *MockIValkeyService) Smembers(ctx context.Context, key string) ([]string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Smembers")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIValkeyService_Smembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Smembers'
type MockIValkeyService_Smembers_Call struct {
	*mock.Call
}

// Smembers is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockIValkeyService_Expecter) Smembers(ctx interface{}, key interface{}) *MockIValkeyService_Smembers_Call {
	return &MockIValkeyService_Smembers_Call{Call: _e.mock.On("Smembers", ctx, key)}
}

func (_c *MockIValkeyService_Smembers_Call) Run(run func(ctx context.Context, key string)) *MockIValkeyService_Smembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIValkeyService_Smembers_Call) Return(strings []string, err error) *MockIValkeyService_Smembers_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockIValkeyService_Smembers_Call) RunAndReturn(run func(ctx context.Context, key string) ([]string, error)) *MockIValkeyService_Smembers_Call {
	_c.Call.Return(run)
	return _c
}

// Sremove provides a mock function for the type MockIValkeyService
func (_mock *MockIValkeyService) Sremove(ctx context.Context, key string, val string) error {
	ret := _mock.Called(ctx, key, val)

	if len(ret) == 0 {
		panic("no return value specified for Sremove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, key, val)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIValkeyService_Sremove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sremove'
type MockIValkeyService_Sremove_Call struct {
	*mock.Call
}

// Sremove is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - val string
func (_e *MockIValkeyService_Expecter) Sremove(ctx interface{}, key interface{}, val interface{}) *MockIValkeyService_Sremove_Call {
	return &MockIValkeyService_Sremove_Call{Call: _e.mock.On("Sremove", ctx, key, val)}
}

func (_c *MockIValkeyService_Sremove_Call) Run(run func(ctx context.Context, key string, val string)) *MockIValkeyService_Sremove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIValkeyService_Sremove_Call) Return(err error) *MockIValkeyService_Sremove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIValkeyService_Sremove_Call) RunAndReturn(run func(ctx context.Context, key string, val string) error) *MockIValkeyService_Sremove_Call {
	_c.Call.Return(run)
	return _c
}

// Sset provides a mock function for the type MockIValkeyService
func (_mock *MockIValkeyService) Sset(ctx context.Context, key string, members []string) error {
	ret := _mock.Called(ctx, key, members)

	if len(ret) == 0 {
		panic("no return value specified for Sset")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = returnFunc(ctx, key, members)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIValkeyService_Sset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sset'
type MockIValkeyService_Sset_Call struct {
	*mock.Call
}

// Sset is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - members []string
func (_e *MockIValkeyService_Expecter) Sset(ctx interface{}, key interface{}, members interface{}) *MockIValkeyService_Sset_Call {
	return &MockIValkeyService_Sset_Call{Call: _e.mock.On("Sset", ctx, key, members)}
}

func (_c *MockIValkeyService_Sset_Call) Run(run func(ctx context.Context, key string, members []string)) *MockIValkeyService_Sset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIValkeyService_Sset_Call) Return(err error) *MockIValkeyService_Sset_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIValkeyService_Sset_Call) RunAndReturn(run func(ctx context.Context, key string, members []string) error) *MockIValkeyService_Sset_Call {
	_c.Call.Return(run)
	return _c
}
