// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserServiceError creates a new instance of MockUserServiceError. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserServiceError(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserServiceError {
	mock := &MockUserServiceError{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserServiceError is an autogenerated mock type for the UserServiceError type
type MockUserServiceError struct {
	mock.Mock
}

type MockUserServiceError_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserServiceError) EXPECT() *MockUserServiceError_Expecter {
	return &MockUserServiceError_Expecter{mock: &_m.Mock}
}

// Error provides a mock function for the type MockUserServiceError
func (_mock *MockUserServiceError) Error() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Error")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockUserServiceError_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockUserServiceError_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
func (_e *MockUserServiceError_Expecter) Error() *MockUserServiceError_Error_Call {
	return &MockUserServiceError_Error_Call{Call: _e.mock.On("Error")}
}

func (_c *MockUserServiceError_Error_Call) Run(run func()) *MockUserServiceError_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUserServiceError_Error_Call) Return(s string) *MockUserServiceError_Error_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockUserServiceError_Error_Call) RunAndReturn(run func() string) *MockUserServiceError_Error_Call {
	_c.Call.Return(run)
	return _c
}
