// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"luny.dev/foodbasket/internal/services"
)

// NewMockISessionService creates a new instance of MockISessionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockISessionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockISessionService {
	mock := &MockISessionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockISessionService is an autogenerated mock type for the ISessionService type
type MockISessionService struct {
	mock.Mock
}

type MockISessionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockISessionService) EXPECT() *MockISessionService_Expecter {
	return &MockISessionService_Expecter{mock: &_m.Mock}
}

// CreateSession provides a mock function for the type MockISessionService
func (_mock *MockISessionService) CreateSession(ctx context.Context, data services.SessionData) (string, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, services.SessionData) (string, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, services.SessionData) string); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, services.SessionData) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockISessionService_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockISessionService_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - data services.SessionData
func (_e *MockISessionService_Expecter) CreateSession(ctx interface{}, data interface{}) *MockISessionService_CreateSession_Call {
	return &MockISessionService_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, data)}
}

func (_c *MockISessionService_CreateSession_Call) Run(run func(ctx context.Context, data services.SessionData)) *MockISessionService_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 services.SessionData
		if args[1] != nil {
			arg1 = args[1].(services.SessionData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockISessionService_CreateSession_Call) Return(sessionID string, err error) *MockISessionService_CreateSession_Call {
	_c.Call.Return(sessionID, err)
	return _c
}

func (_c *MockISessionService_CreateSession_Call) RunAndReturn(run func(ctx context.Context, data services.SessionData) (string, error)) *MockISessionService_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSession provides a mock function for the type MockISessionService
func (_mock *MockISessionService) DeleteSession(ctx context.Context, sessionID string) error {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockISessionService_DeleteSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSession'
type MockISessionService_DeleteSession_Call struct {
	*mock.Call
}

// DeleteSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockISessionService_Expecter) DeleteSession(ctx interface{}, sessionID interface{}) *MockISessionService_DeleteSession_Call {
	return &MockISessionService_DeleteSession_Call{Call: _e.mock.On("DeleteSession", ctx, sessionID)}
}

func (_c *MockISessionService_DeleteSession_Call) Run(run func(ctx context.Context, sessionID string)) *MockISessionService_DeleteSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockISessionService_DeleteSession_Call) Return(err error) *MockISessionService_DeleteSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockISessionService_DeleteSession_Call) RunAndReturn(run func(ctx context.Context, sessionID string) error) *MockISessionService_DeleteSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function for the type MockISessionService
func (_mock *MockISessionService) GetSession(ctx context.Context, sessionID string) (*services.SessionData, error) {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 *services.SessionData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*services.SessionData, error)); ok {
		return returnFunc(ctx, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *services.SessionData); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.SessionData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockISessionService_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type MockISessionService_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockISessionService_Expecter) GetSession(ctx interface{}, sessionID interface{}) *MockISessionService_GetSession_Call {
	return &MockISessionService_GetSession_Call{Call: _e.mock.On("GetSession", ctx, sessionID)}
}

func (_c *MockISessionService_GetSession_Call) Run(run func(ctx context.Context, sessionID string)) *MockISessionService_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockISessionService_GetSession_Call) Return(sessionData *services.SessionData, err error) *MockISessionService_GetSession_Call {
	_c.Call.Return(sessionData, err)
	return _c
}

func (_c *MockISessionService_GetSession_Call) RunAndReturn(run func(ctx context.Context, sessionID string) (*services.SessionData, error)) *MockISessionService_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// RotateSession provides a mock function for the type MockISessionService
func (_mock *MockISessionService) RotateSession(ctx context.Context, sessionID string) (string, error) {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for RotateSession")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockISessionService_RotateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RotateSession'
type MockISessionService_RotateSession_Call struct {
	*mock.Call
}

// RotateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockISessionService_Expecter) RotateSession(ctx interface{}, sessionID interface{}) *MockISessionService_RotateSession_Call {
	return &MockISessionService_RotateSession_Call{Call: _e.mock.On("RotateSession", ctx, sessionID)}
}

func (_c *MockISessionService_RotateSession_Call) Run(run func(ctx context.Context, sessionID string)) *MockISessionService_RotateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockISessionService_RotateSession_Call) Return(newSessionID string, err error) *MockISessionService_RotateSession_Call {
	_c.Call.Return(newSessionID, err)
	return _c
}

func (_c *MockISessionService_RotateSession_Call) RunAndReturn(run func(ctx context.Context, sessionID string) (string, error)) *MockISessionService_RotateSession_Call {
	_c.Call.Return(run)
	return _c
}
