// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIPermissionService creates a new instance of MockIPermissionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPermissionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPermissionService {
	mock := &MockIPermissionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIPermissionService is an autogenerated mock type for the IPermissionService type
type MockIPermissionService struct {
	mock.Mock
}

type MockIPermissionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPermissionService) EXPECT() *MockIPermissionService_Expecter {
	return &MockIPermissionService_Expecter{mock: &_m.Mock}
}

// GetUserPermissions provides a mock function for the type MockIPermissionService
func (_mock *MockIPermissionService) GetUserPermissions(ctx context.Context, userID uuid.UUID, tenantID uuid.UUID) ([]string, error) {
	ret := _mock.Called(ctx, userID, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPermissions")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]string, error)); ok {
		return returnFunc(ctx, userID, tenantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []string); ok {
		r0 = returnFunc(ctx, userID, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID, tenantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPermissionService_GetUserPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserPermissions'
type MockIPermissionService_GetUserPermissions_Call struct {
	*mock.Call
}

// GetUserPermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - tenantID uuid.UUID
func (_e *MockIPermissionService_Expecter) GetUserPermissions(ctx interface{}, userID interface{}, tenantID interface{}) *MockIPermissionService_GetUserPermissions_Call {
	return &MockIPermissionService_GetUserPermissions_Call{Call: _e.mock.On("GetUserPermissions", ctx, userID, tenantID)}
}

func (_c *MockIPermissionService_GetUserPermissions_Call) Run(run func(ctx context.Context, userID uuid.UUID, tenantID uuid.UUID)) *MockIPermissionService_GetUserPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIPermissionService_GetUserPermissions_Call) Return(strings []string, err error) *MockIPermissionService_GetUserPermissions_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockIPermissionService_GetUserPermissions_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, tenantID uuid.UUID) ([]string, error)) *MockIPermissionService_GetUserPermissions_Call {
	_c.Call.Return(run)
	return _c
}
