// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockITenantService creates a new instance of MockITenantService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockITenantService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockITenantService {
	mock := &MockITenantService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockITenantService is an autogenerated mock type for the ITenantService type
type MockITenantService struct {
	mock.Mock
}

type MockITenantService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockITenantService) EXPECT() *MockITenantService_Expecter {
	return &MockITenantService_Expecter{mock: &_m.Mock}
}

// GetTenantID provides a mock function for the type MockITenantService
func (_mock *MockITenantService) GetTenantID(ctx context.Context, slug string) (*uuid.UUID, error) {
	ret := _mock.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetTenantID")
	}

	var r0 *uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*uuid.UUID, error)); ok {
		return returnFunc(ctx, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *uuid.UUID); ok {
		r0 = returnFunc(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockITenantService_GetTenantID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTenantID'
type MockITenantService_GetTenantID_Call struct {
	*mock.Call
}

// GetTenantID is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockITenantService_Expecter) GetTenantID(ctx interface{}, slug interface{}) *MockITenantService_GetTenantID_Call {
	return &MockITenantService_GetTenantID_Call{Call: _e.mock.On("GetTenantID", ctx, slug)}
}

func (_c *MockITenantService_GetTenantID_Call) Run(run func(ctx context.Context, slug string)) *MockITenantService_GetTenantID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockITenantService_GetTenantID_Call) Return(uUID *uuid.UUID, err error) *MockITenantService_GetTenantID_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockITenantService_GetTenantID_Call) RunAndReturn(run func(ctx context.Context, slug string) (*uuid.UUID, error)) *MockITenantService_GetTenantID_Call {
	_c.Call.Return(run)
	return _c
}

// IsTenant provides a mock function for the type MockITenantService
func (_mock *MockITenantService) IsTenant(ctx context.Context, tenantID uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for IsTenant")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, tenantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, tenantID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockITenantService_IsTenant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsTenant'
type MockITenantService_IsTenant_Call struct {
	*mock.Call
}

// IsTenant is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
func (_e *MockITenantService_Expecter) IsTenant(ctx interface{}, tenantID interface{}) *MockITenantService_IsTenant_Call {
	return &MockITenantService_IsTenant_Call{Call: _e.mock.On("IsTenant", ctx, tenantID)}
}

func (_c *MockITenantService_IsTenant_Call) Run(run func(ctx context.Context, tenantID uuid.UUID)) *MockITenantService_IsTenant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockITenantService_IsTenant_Call) Return(b bool, err error) *MockITenantService_IsTenant_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockITenantService_IsTenant_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID) (bool, error)) *MockITenantService_IsTenant_Call {
	_c.Call.Return(run)
	return _c
}
