<!-- Generated by Gemini as placeholder -->
<script setup lang="ts">
import { onMounted, ref } from "vue";

const props = defineProps<{
  tl: any;
}>();

const loading = ref(true);
const error = ref("");
const data = ref<{
  userId: string;
  userEmail: string;
  tenantId: string | null;
  branchId: string | null;
  profileContext: string;
} | null>(null);

async function tryFetchMe() {
  loading.value = true;
  error.value = "";

  try {
    const res = await fetch(`${import.meta.env.PUBLIC_API}/v1/auth/me`, {
      method: "GET",
      mode: "cors",
      credentials: "include",
    });

    if (res.ok) {
      data.value = await res.json();
    } else {
      error.value = "errorUnauthorized";
    }
  } catch {
    error.value = "errorInternet";
  } finally {
    loading.value = false;
  }
}

onMounted(tryFetchMe);
</script>

<template>
  <div class="max-w-md mx-auto mt-8 p-6 bg-white border border-slate-200 rounded-xl shadow-sm">
    <div v-if="loading" class="flex flex-col items-center space-y-4 animate-pulse">
      <div class="w-16 h-16 bg-slate-200 rounded-full"></div>
      <div class="h-4 w-3/4 bg-slate-200 rounded"></div>
      <p class="text-slate-400 text-sm italic">{{ tl.index.loading }}</p>
    </div>

    <div
      v-else-if="error"
      class="flex flex-col items-center text-center p-4 bg-red-50 rounded-lg border border-red-100"
    >
      <div class="text-red-500 mb-2">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="w-8 h-8"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"
          />
        </svg>
      </div>
      <p class="text-red-700 font-medium">{{ tl.index[error] }}</p>
      <button
        @click="tryFetchMe"
        class="mt-3 text-xs font-semibold text-red-600 hover:text-red-800 underline uppercase tracking-wider"
      >
        Try Again
      </button>
    </div>

    <div v-else-if="data" class="flex items-center space-x-4">
      <div class="grow min-w-0">
        <h3 class="text-sm font-medium text-slate-900 truncate">
          {{ data.userEmail }}
        </h3>
        <div class="flex items-center gap-2 mt-1">
          <span
            class="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-slate-100 text-slate-800 border border-slate-200 uppercase"
          >
            {{ data.profileContext }}
          </span>
          <span v-if="data.tenantId" class="text-[10px] text-slate-400">
            ID: {{ data.userId.split("-")[0] }}...
          </span>
        </div>
      </div>
    </div>
  </div>
</template>
